### ISSUE TITLE
Display on/off

### ISSUE THREAD

**Issue by tmedelnick** [derkalle4/python3-idotmatrix-client#10]
Hello,
on the 16x16 display, this worked for me

Display on 5, 0, 7, 1, 1
Display off 5, 0, 7, 1, 0

**Comment by inselberg** [comment]
32x32 too

**Comment by derkalle4** [comment]
Many thanks for your request and testing! @inselberg already has provided a pull request with is not mergeable atm. When this is resolved I'll happily merge it and the feature should work as expected.

**Comment by derkalle4** [comment]
@tmedelnick has been implemented. You can now turn your display on/off with --screen on/off - see README for examples :)
