### ISSUE TITLE
How to Discover Bluetooth Address of iDotMatrix Display on MacBook Pro M1 Max

### ISSUE THREAD

**Issue by hevalito** [derkalle4/python3-idotmatrix-client#17]
Hello,

I'm currently using a MacBook Pro M1 Max with the BCM_4387 Bluetooth chip and I'm trying to connect to an iDotMatrix Display via Bluetooth. However, I'm having difficulty discovering the device's Bluetooth address. 

Could you please provide guidance or instructions on how to find the Bluetooth address of the iDotMatrix Display using this specific hardware setup? Is there a common method or a specific procedure I should follow on macOS to ensure the device is correctly identified and paired?

Any help or tips regarding this would be greatly appreciated, as I'm unable to pair the device due to this issue.

Thank you for your help!

**Comment by derkalle4** [comment]
Hi @hevalito 

many thanks for your issue :) currently our tool does not support discovery of bluetooth devices. This will be added and I will use your issue to keep track of it.

If you are somewhat familiar with python (3) you should be able to discover all bluetooth devices via
`import asyncio
from bleak import BleakScanner

async def main():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d)

asyncio.run(main())`

(More information can be found here: https://github.com/hbldh/bleak)

**Comment by hevalito** [comment]
Thank you for the quick reply. I'm somehow afraid my on board BT chip on the MAc doesn't discover the device at all. I can find it with my Phone using BT Inspector - but my Mac doesn't see it. Is the dot matrix display running a newer version of BT that my Mac potentially can't work with?

**Comment by hevalito** [comment]
Follow up: I was wrong. When disconnected from my phone, the device shows up. But bleak only gives me the UUID. What I need is the MAC address to connect to the device, right?

**Comment by hevalito** [comment]
Update: I just tested, and it seems your client also accepts the UUID as device address! It works! :)

**Comment by derkalle4** [comment]
Great to hear! Seems that bleak does also work with the UUID. However, there will be something to discover devices. Wasn't sure if someone ever will find my repository but now it seems like everyone knows about it :D

I'll let you know when we have integrated something to discover devices!

**Comment by hevalito** [comment]
Great! I already wrote a little script using Pillow to get the current weather, and send it to the display via the DIY mode. Love it so far. Are you planning on releasing the client as a library? 
![IMG_6729](https://github.com/derkalle4/python3-idotmatrix-client/assets/79545140/133ee698-aa01-43f3-a2bd-962dd28db276)

**Comment by greguu** [comment]
Wow, must be really cold ..

@hevalito  How do you do the DIY mode, create custom PNG somehow and send it to the screen ?

**Comment by hevalito** [comment]
Yes, I did it in a "hacky" way a bit.

I have multiple functions. 
- One that formats the content to fit the screen: `format_text_for_display`
- Rendering an image with the content with Pillow: `create_image_with_text`
- Extracting the pixels from the 32x32 image to build the Array for the Dot Matrix: `extract_pixels_from_image`
- Sending the pixels to the idotmatrix with subprocess: `send_pixel_data_to_idotmatrix`

Eventually you just call the functions like that: 

Font path points to a ttf font. 

```
                image = create_image_with_text(display_text, font_path)
                pixels = extract_pixels_from_image(image)
                send_pixel_data_to_idotmatrix(' '.join(pixels), device_id)
```

```
def format_text_for_display(text, max_width, max_height, font_path, min_font_size=8):
    """Dynamically formats text to fit within the specified dimensions."""
    font_size = 20  # Start with a larger font size
    while font_size >= min_font_size:
        font = ImageFont.truetype(font_path, font_size)
        wrapped_text = textwrap.fill(text, width=max_width // font_size * 2)
        w, h = ImageDraw.Draw(Image.new('RGB', (1, 1))).multiline_textsize(wrapped_text, font=font)
        if w <= max_width and h <= max_height:
            return wrapped_text, font
        font_size -= 1
    # If it doesn't fit even with the smallest font, use the smallest font and wrap the text
    font = ImageFont.truetype(font_path, min_font_size)
    wrapped_text = textwrap.fill(text, width=max_width // min_font_size * 2)
    return wrapped_text, font

def create_image_with_text(text, font_path, max_width=32, max_height=32):
    """Creates an image with the given text formatted to fit within the matrix."""
    formatted_text, font = format_text_for_display(text, max_width, max_height, font_path)
    image = Image.new('RGB', (max_width, max_height), color='black')
    draw = ImageDraw.Draw(image)
    draw.multiline_text((0, 0), formatted_text, fill='white', font=font)
    return image

def extract_pixels_from_image(image):
    """Extracts colored pixel data from an image."""
    pixels = []
    for y in range(32):
        for x in range(32):
            pixel = image.getpixel((x, y))
            if pixel != (0, 0, 0):  # Check if pixel is not black
                pixels.append(f"{x}-{y}-{pixel[0]}-{pixel[1]}-{pixel[2]}")
    return pixels

def send_pixel_data_to_idotmatrix(pixel_data, device_id):
    """Sends pixel data to the iDotMatrix device."""
    command = f"python3 app.py --address {device_id} --pixel-color {pixel_data}"
    subprocess.run(command, shell=True)
```

**Comment by hevalito** [comment]
Don't forget to
```
from PIL import Image, ImageDraw, ImageFont
import subprocess
import textwrap
```

**Comment by derkalle4** [comment]
@hevalito currently no plans to migrate this into a library because my current approach would be to reverse engineer stuff first. But I think it's a good idea to take this further afterwards and create a library which can be consumed by this project.

Let me put this to the roadmap. Would be good to have this handy for other use cases.

However, I wouldn't integrate Bleak into that library and only return the bytecode necessary to talk to the device.

**Comment by derkalle4** [comment]
Nice picture btw :) the display has some kind of text mode which will be implemented. Maybe that would make things even better.

**Comment by hevalito** [comment]
Of course! I wanted to get content onto the screen and that was a rapid way to get it done. :-) 
More questions: 
- Is it possible to add multiple screens and "chain" them together? Would be a nice mode.
- Is it possible to conneect the device via USB and talk to it? Potentially this opens up the possibility to build a raspberry pi or similar to let it run in some kind of standalone mode.

**Comment by derkalle4** [comment]
For the first question: it is on my roadmap to support multiple devices and send data to them to act like one big screen. Unfortunately my second 32 pixel display got declined by DHL due to something wrong with the package. Currently waiting for Aliexpress to figure that out.

For your second question: I haven't looked into the usb port nor opened the device to check whether there is actually a connection to mess with the device. At least I did not get it to show up on my computer. Therefore it seems to be disabled at least.

**Comment by schorsch3000** [comment]
> I haven't looked into the usb port nor opened the device to check whether there is actually a connection to mess with the device.

It's not connected.
i opened my 32x32 out of curiosity. 
there is a 2 wire cable from the mini pcb that holds the usb socket.
the hole between the buttons and the beeper hole are fake too, yes, there is a beeper and a mic, but there are just on the pcb in another position :-D

**Comment by derkalle4** [comment]
Thanks for clarification :) any UART or other stuff to program that thing? ^^

**Comment by schorsch3000** [comment]
So, there are some pads...
There is pr0 and pr1 next to each other.
PA9 standing alone, PC4 also by it self, TX and RX(!) and 6 pads which i think is the actuall usb connection and maybe the 2 buttons?
VDD
USBM
USBP
GND
KEY1
KEY2

Thats the relevent part of that PCB:
![image](https://github.com/derkalle4/python3-idotmatrix-client/assets/2485762/c07bce0e-43d0-45f4-994d-ef911aa3c490)

apart from that there are 2 caps and what i think are the display drivers (but there are 2 types of ic's)

![image](https://github.com/derkalle4/python3-idotmatrix-client/assets/2485762/257e478a-deb5-45ce-91b7-619c77396df2)

![image](https://github.com/derkalle4/python3-idotmatrix-client/assets/2485762/e021ffc0-4112-4702-9ec9-eb5ea54f7b12)



Its quite easy to open up, just the 8 visible screws, no clips nothing else.
BUT, its hard to remove the pcb from the back, seems like at first the usb and button pcb was screwed into the back, than wires are soldered. can be done, but its fiddly.

**Comment by derkalle4** [comment]
Interesting! Many Thanks! Now we need someone who wants to get the firmware of the device and reverse engineer that part and then we have a definitely good solution :D best would be to have firmware updates over bluetooth. But thats something for later. First stretch goal is to reverse-engineer everything before checking on how to further improve the software of the device itself.

**Comment by derkalle4** [comment]
Hi, to get back to the initial topic of this request: I have splitted the connection part into a separared repository. Will need some days to implement everything into this client but afterwards there should be a working client lookup as well as an automatic connection to the first available client if any is found :)

**Comment by derkalle4** [comment]
For early adopters: https://github.com/derkalle4/python3-idotmatrix-library

Please bare with me until I have updated the readme and added the library to pip.

Follow the repo or wait until I reply to this issue to follow the progress.

**Comment by derkalle4** [comment]
Hi @hevalito 

I have added the following commands to this project which should help with your initial request. In case you have problems please re-open this issue. If there is a follow up for the other discussed topics please create a new issue to have one issue per problem/request.

Specifies the address of the pixel display device. Use "auto" to use the first available device (automatically looking for IDM-* devices in range).

```sh
./run_in_venv.sh --address 00:11:22:33:44:ff
```

Scans all bluetooth devices in range for iDotMatrix devices. Quits afterwards. Cannot be combined with other commands (use --address auto instead).

```sh
./run_in_venv.sh --scan
```

Kind Regards,
Kalle

**Comment by ThatCarrot** [comment]
> So, there are some pads... There is pr0 and pr1 next to each other. PA9 standing alone, PC4 also by it self, TX and RX(!) and 6 pads which i think is the actuall usb connection and maybe the 2 buttons? VDD USBM USBP GND KEY1 KEY2

any update on the wired connection?
was thinking of making this a smart device with arduino using UART and sinric or maybe a custom skill :) 

_btw kudos for the excellent work_
