### ISSUE TITLE
Works in Windows 11 with MS supplied python3

### ISSUE THREAD

**Issue by realhagie** [derkalle4/python3-idotmatrix-client#22]
Just a note. 
It works on Windows 11 using the Terminal, python installed from Microsoft marketplace (pip is  included). 
I do not use venv, I just use "pip install ." in the cloned repository. After that I could use the app.py without any problems.
may not the best way to have it run (no venv) but it works inluding vonversion of svg / gif animations.
Thanks !

**Comment by derkalle4** [comment]
Hi @realhagie,
many thanks for your feedback :) will check on include for the docs once the reverse-engineering part got finished.
