### ISSUE TITLE
Some info about how to obtain devices address would be nice.

### ISSUE THREAD

**Issue by davince72** [derkalle4/python3-idotmatrix-client#25]
Could you write some documentation on how to acuire the device's address needed to run the tool?
I received device today and used iphone app and was connected right away....but have no idea where to find the address (the device doen not show up on my laptop either)

**Comment by realhagie** [comment]
I use an android app called BLE Scanner. It shows the mac address of the device. There are many out there , no knowledge about apple tho.

**Comment by davince72** [comment]
Thanks for that tip! I tried several, but the ones i tried don't list the address :-( Only some other data, but will continue my search. Thanks!

**Comment by derkalle4** [comment]
Hi, this will be implemented. I am sorry that I have not that much time to spend on this project. But I'll do something to be able to obtain the device mac address :)
