### ISSUE TITLE
Make gif or image persistant.

### ISSUE THREAD

**Issue by Duberry** [derkalle4/python3-idotmatrix-client#37]
Does anybody know if it is possible to make a gif or image persist on the device between power cycles?

**Comment by derkalle4** [comment]
Hi @Duberry,

unfortunately that does not seem possible. At least there is nothing that I am aware of and some kind of limitation of the device. Currently we do not have the firmware reverse-engineered and without help that can not be done.

Kind Regards,
Kalle
