### ISSUE TITLE
Text & GIF uploading

### ISSUE THREAD

**Issue by 8none1** [derkalle4/python3-idotmatrix-client#4]
Hi team,

I've got one of these devices too, it's quite fun!

I've worked out how to send my own text and GIFs to it and have a very rudimentary Python script to help.

Your project looks much tidier than mine, so I thought I point you at this in case it's useful:

https://github.com/8none1/idotmatrix

**Comment by derkalle4** [comment]
Hey Will,

many thanks for providing some additional source code. It'll definitely help me to add further features. If you don't mind I would add your name and github account to the README and use the source code to extend my project.

Kind Regards,
Kalle

**Comment by 8none1** [comment]
Sure thing!  I can try and get a PR up for you, but it might take a few days.

**Comment by derkalle4** [comment]
No worries, take your time! Wish you a merry christmas! This is only a small fun project and I do not have figured out how to do things "the right way". Feel free to drop a PR when I haven't got the time to implement it. Otherwise feel free to improve things you think one can make better :)

**Comment by derkalle4** [comment]
For your information: I've successfully implemented the GIF upload! Many thanks for your reverse-engineering efforts! I will work on the text processing soon.

**Comment by 8none1** [comment]
That's excellent!!
