### ISSUE TITLE
No Module named ''idotmatrix'

### ISSUE THREAD

**Issue by supremedk1985** [derkalle4/python3-idotmatrix-client#47]
Debian (VM) , Python3/Pip installed with "sudo apt-get install python3" and "python3-pip"

After changing the pip3 > pip because of  #https://github.com/derkalle4/python3-idotmatrix-client/issues/35 i come to the next problem calling "python3 .\app.py scan" or "./run_in_venv.sh --scan"
it ends with the error that ther is no Module named ''idotmatrix'.

```
  File "/home/osboxes/python3-idotmatrix-client/app.py", line 7, in <module>
    from core.cmd import CMD
  File "/home/osboxes/python3-idotmatrix-client/core/cmd.py", line 9, in <module>
    from idotmatrix import ConnectionManager
ModuleNotFoundError: No module named 'idotmatrix'

```
(I also tried it on my PI3 with exactly the same behaviour)

I'm not familiar with python and linux, so i hope you can help. Thanks a lot.

**Comment by schorsch3000** [comment]
did you create an venv in the first place ( by running create_venv.sh or by hand)?

**Comment by supremedk1985** [comment]
Yes, without a Problem. But how can i Check if its created succesfully?

**Comment by schorsch3000** [comment]
could you run `bash -x run_in_venv.sh --scan` and show the output?

creating a venv should result in a directory called venv :-)

**Comment by supremedk1985** [comment]
Sorry for the delay. I couldn't get it working on any OS, which was quite frustrating. Because of that, I ended up returning the LED matrix to China. I'm not sure how to proceed from here—should I just close the issue?

**Comment by ellensp** [comment]
you have to build and install https://github.com/derkalle4/python3-idotmatrix-library  also

**Comment by derkalle4** [comment]
@ellensp that should not be necessary. There is an up to date built pip module here: https://pypi.org/project/idotmatrix/ which should be available. Anyway: sorry for not looking into this but a manual "pip install idotmatrix" should work.

I am going to close this because author has returned his device.
