### ISSUE TITLE
No such file or directory: '/tmp/pip-req-build-zbr38sa1/setup.py'

### ISSUE THREAD

**Issue by TomCat666** [derkalle4/python3-idotmatrix-client#49]
Hi

Spent a few hours today trying to build on rpi3 but whatever I do I get the error:

 No such file or directory: '/tmp/pip-req-build-zbr38sa1/setup.py'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-zbr38sa1/

When doing ./create_venv.sh

I had to change the pip3 to pip in find_cmds.sh  otherwise I just got the error that it cannot find pip3

Not that at home with python... I tried different things like 

python3 -m ensurepip --upgrade

sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 3

 pip install ez_setup

But in the end I always got the same error...

**Comment by schorsch3000** [comment]
Hi,
yep, there is #35, which addresses exactly this :-)

**Comment by TomCat666** [comment]
Thank you ! :)

python3 -m pip install ./

This worked in the end...
